# Generated by Django 3.0.2 on 2020-02-13 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200213_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('thumbnial', models.FileField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=1000)]),
        ),
    ]
