# Generated by Django 3.0.2 on 2020-02-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_bookorder_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
