# Generated by Django 3.0.2 on 2020-02-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_article_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='removed',
        ),
    ]
