# Generated by Django 3.0.2 on 2020-02-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('publish_article', '哈哈哈 publish article'), ('comment_article', 'Can comment article'))},
        ),
    ]
