# Generated by Django 3.0.2 on 2020-02-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200217_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('publish_article', 'Can publish article'), ('comment_article', 'Can comment article'))},
        ),
    ]
